version: '3.8'

services:

    # PHP Service container
    app:
        platform: linux/amd64
        build:
            args:
                user: pastojakub
                uid: 1000
            context: .
            dockerfile: ./Dockerfile
        image: technova_app
        container_name: technova_app_container
        restart: unless-stopped
        depends_on:
            -   db
        working_dir: /var/www
        volumes:
            -   ./:/var/www
        networks:
            - technova_network

    #nginx service
    web:
        platform: linux/amd64
        image: nginx:alpine
        container_name: technova_web_container
        restart: unless-stopped
        ports:
            - "80:80"
        depends_on:
            -   app
        volumes:
            -   ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d
        networks:
            - technova_network

    #mysql service
    db:
        platform: linux/amd64
        image: mysql
        container_name: technova_mysql_container
        restart: unless-stopped
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: technova_db
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        volumes:
            -   technova_mysql_data:/var/lib/mysql
        networks:
            - technova_network

    phpmyadmin:
        image: phpmyadmin:5.2.1-apache
        container_name: technova_phpmyadmin_container
        restart: unless-stopped
        ports:
            -   "8080:80"
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
            PMA_USER: root
            PMA_PASSWORD: password
        depends_on:
            -   db
        networks:
            - technova_network

    redis:
        image: redis:7.2-alpine
        container_name: technova_redis_container
        ports:
            -   "7379:6379"
        networks:
            - technova_network
volumes:
    technova_mysql_data:
        driver: local

networks:
    technova_network:
        driver: bridge
